# Generated by Django 5.2.4 on 2025-07-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pr_images',
        ),
        migrations.AddField(
            model_name='product',
            name='pr_image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
