# Generated by Django 5.2.4 on 2025-07-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_pr_images_product_pr_image_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pr_image_data',
        ),
        migrations.AddField(
            model_name='product',
            name='pr_images',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
